cmake_minimum_required(VERSION 4.2.3) #показывает какой минимальной версией можно собрать проект

project(Fursov_test) #дает имя проекту

#дает понять что будет собираться исполняеый файл(exe)
#первый аргумент - это название собираемоего проекта, остальные исходные файлы *.h *.cpp
#все аргументы записываются через пробел
add_executable(main prog_one/prog1.cpp lib.cpp) 
